-- MySQL Script generated by MySQL Workbench
-- 05/16/16 20:47:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Uam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Uam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Uam` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `Uam` ;

-- -----------------------------------------------------
-- Table `Uam`.`UEA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Uam`.`UEA` (
  `cveUEA` INT NOT NULL,
  `nomUEA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cveUEA`),
  UNIQUE INDEX `idUEA_UNIQUE` (`cveUEA` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Uam`.`Roll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Uam`.`Roll` (
  `idRoll` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoll`),
  UNIQUE INDEX `idRoll_UNIQUE` (`idRoll` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Uam`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Uam`.`Profesor` (
  `cveEmp` INT NOT NULL,
  `nomProfesor` VARCHAR(45) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `roll` INT NOT NULL,
  PRIMARY KEY (`cveEmp`),
  INDEX `roll_idx` (`roll` ASC),
  CONSTRAINT `roll`
    FOREIGN KEY (`roll`)
    REFERENCES `Uam`.`Roll` (`idRoll`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Uam`.`TareasGenericas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Uam`.`TareasGenericas` (
  `idTareaG` INT NOT NULL,
  `cveProfesor` VARCHAR(45) NOT NULL,
  `cveUEA` INT NOT NULL,
  `nomTarea` VARCHAR(30) NOT NULL,
  `descTarea` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTareaG`),
  UNIQUE INDEX `idTareaG_UNIQUE` (`idTareaG` ASC),
  INDEX `fk_TareasGenericas_UEA1_idx` (`cveUEA` ASC),
  CONSTRAINT `fk_TareasGenericas_UEA1`
    FOREIGN KEY (`cveUEA`)
    REFERENCES `Uam`.`UEA` (`cveUEA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Uam`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Uam`.`Curso` (
  `idCurso` INT NOT NULL,
  `UEA` INT NOT NULL,
  `cveProfesor` INT NOT NULL,
  `Trimestre` VARCHAR(3) NOT NULL,
  `cveCurso` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`idCurso`),
  UNIQUE INDEX `idCurso_UNIQUE` (`idCurso` ASC),
  INDEX `UEA_idx` (`UEA` ASC),
  INDEX `Profesor_idx` (`cveProfesor` ASC),
  CONSTRAINT `UEA`
    FOREIGN KEY (`UEA`)
    REFERENCES `Uam`.`UEA` (`cveUEA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Profesor`
    FOREIGN KEY (`cveProfesor`)
    REFERENCES `Uam`.`Profesor` (`cveEmp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Uam`.`TareasCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Uam`.`TareasCurso` (
  `idTareaCurso` INT NOT NULL,
  `idTareaG` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `nomTareaCurso` VARCHAR(30) NOT NULL,
  `descTareaCurso` VARCHAR(100) NULL,
  PRIMARY KEY (`idTareaCurso`),
  INDEX `NumTarea_idx` (`idTareaG` ASC),
  INDEX `fk_TareasCurso_Curso1_idx` (`idCurso` ASC),
  CONSTRAINT `NumTarea`
    FOREIGN KEY (`idTareaG`)
    REFERENCES `Uam`.`TareasGenericas` (`idTareaG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TareasCurso_Curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `Uam`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Uam`.`ListaAlumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Uam`.`ListaAlumno` (
  `Matricula` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `nomAlumno` VARCHAR(45) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `roll` INT NOT NULL,
  PRIMARY KEY (`Matricula`),
  INDEX `Curso_idx` (`idCurso` ASC),
  INDEX `roll_idx` (`roll` ASC),
  CONSTRAINT `Curso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `Uam`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roll`
    FOREIGN KEY (`roll`)
    REFERENCES `Uam`.`Roll` (`idRoll`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Uam`.`CalificacionTarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Uam`.`CalificacionTarea` (
  `idCalificacion` INT NOT NULL,
  `NumTarea` INT NOT NULL,
  `aciertos` INT NOT NULL,
  `Matricula` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `numIntentos` INT NOT NULL,
  PRIMARY KEY (`idCalificacion`),
  INDEX `Calificaciones_idx` (`NumTarea` ASC),
  INDEX `Alumno_idx` (`Matricula` ASC),
  CONSTRAINT `Tarea`
    FOREIGN KEY (`NumTarea`)
    REFERENCES `Uam`.`TareasCurso` (`idTareaG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Alumno`
    FOREIGN KEY (`Matricula`)
    REFERENCES `Uam`.`ListaAlumno` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Uam`.`Vistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Uam`.`Vistas` (
  `idVistas` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `roll` INT NOT NULL,
  PRIMARY KEY (`idVistas`, `roll`),
  UNIQUE INDEX `idVistas_UNIQUE` (`idVistas` ASC),
  INDEX `fk_Vistas_Roll1_idx` (`roll` ASC),
  CONSTRAINT `fk_Vistas_Roll1`
    FOREIGN KEY (`roll`)
    REFERENCES `Uam`.`Roll` (`idRoll`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
